// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbhkrbonodcucvbccwxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiaGtyYm9ub2RjdWN2YmNjd3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDk2NjgsImV4cCI6MjA3MDM4NTY2OH0.nnviaQJpCaTgw2a08JMyHldoGCQjxciJ_Vt5TD-hkjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});